-- 035 — chat history provider provenance.
-- Adds nullable metadata to rag_messages so restored conversations can repaint answer-level badges
-- such as Gemini fallback / model provenance. Backward-compatible: old rows remain NULL.

alter table public.rag_messages
  add column if not exists provider text,
  add column if not exists model text,
  add column if not exists fallback boolean;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rag_messages_provider_check'
      and conrelid = 'public.rag_messages'::regclass
  ) then
    alter table public.rag_messages
      add constraint rag_messages_provider_check
      check (provider is null or provider in ('anthropic', 'gemini'));
  end if;
end $$;

comment on column public.rag_messages.provider is
  'LLM provider that generated an assistant message: anthropic or gemini. NULL for legacy/user rows.';
comment on column public.rag_messages.model is
  'LLM model id used for the assistant message. NULL for legacy/user rows.';
comment on column public.rag_messages.fallback is
  'True when the assistant message was generated by fallback provider because the primary provider was unavailable.';

